# Site settings
title: Herbert Hsu
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Herbert Hsu
user_description: I am a mechanical engineer with experience in rapid prototyping, design and development of consumer and industrial products. This site contains some projects I’ve done for my classes and some side projects I’ve done during my free time.
#user_title: Software Developer
email: herbhsu@umich.edu
twitter_username: lorem_ipsum
github_username:  herberthsu505
linkedin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
